Lesson10
Sergey113222/dev pull request #5
Opened 2020-09-12 18:23 UTC by Sergey113222

Медленно но не сдаемся
))))

2020-09-15 09:31 UTC, RomanKashenok requested changes
Almost cool :) fix a little regarding to comments and merge

2020-09-15 09:31 UTC, RomanKashenok commented on src/Lesson10/Task29.java
> +        Integer score;
Why do you need 'score' variable here? You can directly assign result of (int) (Math.random() * 10) expression to scores List. Remove it please

2020-09-15 09:31 UTC, RomanKashenok commented on src/Lesson10/Task29.java
> +package Lesson10;
name packages with lowercase letters

2020-09-15 09:31 UTC, RomanKashenok commented on src/Lesson10/Task31.java
> +        Integer score;
remove 'score'

2020-09-25 11:46 UTC, merged

2020-09-25 11:46 UTC, Sergey113222 commented
111

2020-09-25 11:46 UTC, Sergey113222 commented
aa

2020-09-25 11:46 UTC, Sergey113222 commented
ok